# insecure-registry-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-registry-ca
  namespace: kube-system
data:
  registries.conf: |
    unqualified-search-registries = ["docker.io"]
    [[registry]]
      prefix = "registry.kube-system.svc.cluster.local:5000"
      insecure = true
      location = "registry.kube-system.svc.cluster.local:5000"