apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          env:
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
#            - name: REGISTRY_HTTP_TLS
#              value: "false"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: "/var/lib/registry"
#            - name: minikube-certs
#              mountPath: "/certs"
#              readOnly: true
#          env:
#            - name: REGISTRY_HTTP_TLS_CERTIFICATE
#              value: "/certs/apiserver.crt"  # Minikube's API server cert
#            - name: REGISTRY_HTTP_TLS_KEY
#              value: "/certs/apiserver.key"   # Minikube's API server key

      volumes:
#        - name: minikube-certs
#          hostPath:
#            path: "/var/lib/minikube/certs"  # Minikube's cert directory
#            type: Directory
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort  # Makes registry accessible outside the cluster