apiVersion: v1

kind: Secret
metadata:
  name: airflow
type: Opaque

stringData:
  AIRFLOW__CORE__FERNET_KEY: "{{ airflow_core_fernet_key }}"
  AIRFLOW__WEBSERVER__SECRET_KEY: "{{ airflow_webserver_secret_key }}"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "{{ airflow_webserver_expose_config }}"
  webserver-secret-key: "{{ webserver_secret_key }}"
  AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"