server:
  service:
    nodePorts:
      http: "30280"
      https: "30280"

  extraScrapeConfigs:
#    - job_name: trade-bots-farm
#      static_configs:
#        - targets: [ 'trade-bots-farm:8000' ]
    - job_name: 'pushgateway'
      honor_labels: true  # Important to preserve original job labels
      honor_timestamps: true
      scrape_interval: 10s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      scheme: 'http'
      static_configs:
        - targets: ['prometheus-pushgateway:9091']