[project]
name = "trade-bots-farm-process-run-all"
version = "0.1.0"
description = "Start all streams and do all batch processing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "trade-bots-farm-common",
    ]

