version: 1
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: NOTSET
    formatter: classFuncLine
    stream: ext://sys.stdout

formatters:
  classFuncLine:
    format: "%(asctime)s -  %(module)s.%(funcName)s:%(lineno)d  - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%s"

loggers:
  root:
    level: INFO
    handlers: [ consoleHandler ]
  KafkaWithS3Feed:
    level: INFO
    handlers: [ consoleHandler ]
    propagate: no
  FeaturesKafkaProducer:
    level: INFO
    handlers: [ consoleHandler ]
    propagate: no
  MultiIndiFeaturesCalc:
    level: INFO
    handlers: [ consoleHandler ]
    propagate: no
