apiVersion: v1

kind: Secret
metadata:
  name: minio
type: Opaque

stringData:
  endpoint-url: "{{ minio_endpoint_url }}"
  root-user: "{{ minio_root_user }}"
  root-password: "{{ minio_root_password }}"
  access-key: "{{ minio_access_key }}"
  secret-key: "{{ minio_secret_key }}"