apiVersion: v1

kind: Secret
metadata:
  name: mlflow-postgresql
#  labels:
#    app.kubernetes.io/managed-by: Helm
#  annotations:
#    meta.helm.sh/release-name: mlflow
#    meta.helm.sh/release-namespace: default

type: Opaque

stringData:
  password: "{{ mlflow_postgresql_password }}"
  postgres-password: "{{ mlflow_postgresql_postgres_password }}"