apiVersion: v1

kind: Secret
metadata:
  name: mlflow-tracking
type: Opaque

stringData:
  admin-user: "{{ mlflow_tracking_admin_user }}"
  admin-password: "{{ mlflow_tracking_admin_password }}"
  flask-server-secret-key: "{{ mlflow_tracking_flask_server_secret_key }}"