[project]
name = "trade-bots-farm-connector-stream-alor"
version = "0.1.0"
description = "Alor websocket connector"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "trade-bots-farm-common",
    "requests",
    "prometheus-client",
    "s3fs"
    ]
