{
 "title": "Connectors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Htx stream connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Level 2 htx messages per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(connector_stream_htx__messages_processed_total{topic=\"raw.htx.market.btc-usdt.depth.step13\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Level2 htx time lag seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "connector_stream_htx__time_lag_sec{topic=\"raw.htx.market.btc-usdt.depth.step13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles htx messages per 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(connector_stream_htx__messages_processed_total{topic=\"raw.htx.market.btc-usdt.kline.1min\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles htx time lag seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "connector_stream_htx__time_lag_sec{topic=\"raw.htx.market.btc-usdt.kline.1min\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "External S3 batch connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Level2 files downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "connector_batch_s3_external__files_transferred_total{external_s3_dir=\"pytrade2/data/raw/level2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles files downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "connector_batch_s3_external__files_transferred_total{external_s3_dir=\"pytrade2/data/raw/candles\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}