{
 "title": "Preprocessors",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Stream preproc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Level2 input msg/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_stream_staging__messages_input_total{topic=\"raw.htx.market.btc-usdt.depth.step13\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Level2 output msg/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_stream_staging__messages_output_total{topic=\"staging.btc-usdt.level2.1min\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Level2 time lag, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "process_stream_staging__time_lag_sec{topic=\"market.BTC-USDT.depth.step13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles input per sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_stream_staging__messages_input_total{topic=\"raw.htx.market.btc-usdt.kline.1min\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles output per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_stream_staging__messages_output_total{topic=\"staging.btc-usdt.candles.1min\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles time lag, sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "process_stream_staging__time_lag_sec{topic=\"market.BTC-USDT.kline.1min\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batch preproc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Level2 preprocessed daily files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_batch_staging__files_transferred_total{preproc_s3_dir=\"trade-bots-farm/data/preproc/BTC-USDT/level2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Candles preprocessed daily files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "process_batch_staging__files_transferred_total{preproc_s3_dir=\"trade-bots-farm/data/preproc/BTC-USDT/candles\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}