apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-volume-data
  namespace: trade-bots-farm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard