apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: alor-s3-sink
  labels:
    strimzi.io/cluster: kafka-connect-s3
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  config:
    # Kafka topics
    topics: raw.alor.MOEX.TQBR.SBER.candles.1min,raw.alor.MOEX.TQBR.SBER.bid_ask,raw.alor.MOEX.TQBR.SBER.level2

    # s3 base folder
    topics.dir: data/raw/alor

    # File rotation
    rotate.interval.ms: 3600000  # Rotate every hour
    flush.size: 100000  # Large number to prioritize time-based rotation

    # Required configurations
    s3.bucket.name: trade-bots-farm
    storage.class: io.confluent.connect.s3.storage.S3Storage
    store.url: "http://minio:9000"

    # Store in s3 as compressed json.gz
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    s3.compression.type: gzip

    # path format pattern convention:
    # yyyy - year
    # 'year='yyyy - literal text 'year=' then year value
    # literals are in single quotes, values are not
    # The whole construction is a string value in double quotes
    path.format: "'year='yyyy'/month='MM'/day='dd"

    # Time-based partitioning (required for path formatting)
    partitioner.class: io.confluent.connect.storage.partitioner.TimeBasedPartitioner
    partition.duration.ms: 3600000  # 1 hour partition duration (must be positive)
    timestamp.extractor: Wallclock  # Use system time


    # Timezone settings
    timezone: Europe/Moscow
    locale: en-US