apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-s3
  namespace: trade-bots-farm
  annotations:
    strimzi.io/use-connector-resources: "true"  # Enable KafkaConnector CRDs
spec:
  version: 4.0.0  # Must match your Kafka cluster version
  image: quay.io/strimzi/kafka:0.46.1-kafka-4.0.0  # Standard Strimzi image  replicas: 1
  bootstrapServers: "trade-bots-farm-kafka-bootstrap:9092"
  config:
    group.id: "kafka-connect-s3"
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"

    #plugin.path: "/kafka/connect,/kafka/connect/external"  # Debezium-specific path

    # MinIO specific settings (if using MinIO instead of S3)
    s3.endpoint: "http://192.168.49.2:31900"  # Omit if using AWS S3
    s3.path.style.access: "true"              # Required for MinIO
  externalConfiguration:
    env:
      - name: AWS_ACCESS_KEY_ID      # For MinIO access key
        valueFrom:
          secretKeyRef:
            name: minio
            key: access-key
      - name: AWS_SECRET_ACCESS_KEY  # For MinIO secret key
        valueFrom:
          secretKeyRef:
            name: minio
            key: secret-key
  build:
    output:
      type: docker
      image: 192.168.49.2:5000/kafka-connect-s3:latest
      #pushSecret: minikube-registry-credentials
    plugins:
      - name: s3-sink
        artifacts:
          - type: zip
            url: https://hub-downloads.confluent.io/api/plugins/confluentinc/kafka-connect-s3/versions/10.6.7/confluentinc-kafka-connect-s3-10.6.7.zip
