apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-s3
  namespace: trade-bots-farm
  annotations:
    strimzi.io/use-connector-resources: "true"  # Enable KafkaConnector CRDs

spec:
  version: 4.0.0  # Must match your Kafka cluster version
  #image: quay.io/strimzi/kafka:0.46.1-kafka-4.0.0  # Standard Strimzi image  replicas: 1
  image: registry.kube-system.svc.cluster.local:5000/kafka-connect-s3:latest
  #image: 192.168.39.36:30500/kafka-connect-s3:latest
  bootstrapServers: "trade-bots-farm-kafka-bootstrap:9092"
  config:
    group.id: "kafka-connect-s3"
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"


    # MinIO specific settings (if using MinIO instead of S3)
    s3.endpoint: "http://minio:900"  # Omit if using AWS S3
    s3.path.style.access: "true"              # Required for MinIO
  externalConfiguration:
    env:
      - name: AWS_ACCESS_KEY_ID      # For MinIO access key
        valueFrom:
          secretKeyRef:
            name: minio
            key: access-key
      - name: AWS_SECRET_ACCESS_KEY  # For MinIO secret key
        valueFrom:
          secretKeyRef:
            name: minio
            key: secret-key
