[project]
name = "trade-bots-farm-process-stream-full"
version = "0.1.0"
description = "run streaming"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    #"google-re2==0.0.0",  # exclude google providers with their errors
    "trade-bots-farm-common",
    ]

