apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: trade-bots-farm  # e.g., "airflow" if using the airflow namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi  # Adjust size as needed
  storageClassName: standard  # For Minikube, use "standard" or the appropriate class